### ISSUE TITLE
Ignore List and !staff cool down period

### ISSUE THREAD

**Issue by Seahorseruler** [wikimedia/countervandalism-cvn-clerkbot#3]
I propose the following additions to CVNClerkBot and wanted to get your thoughts:
- An Ignore List that ignores by hostname or nick for users who misuse the !staff command. 
  - Users who are on the ignore list will instead be PMed "This function is currently not available. Please visit #countervandalism for help."
- A Cool Down period for the !staff command that will limit how often it can be used.
  - For example, if we want to restrict usage of !staff to once every 5 minutes per person, set the cool down to 300 seconds. If the same user tries to use the command again before the time is up, they will be automatically asked to wait for a response to their original inquiry before trying again.

**Comment by Az1568** [comment]
This is currently being abused in multiple channels to flood out the bot. Needs to be fixed as soon as possible.

**Comment by Krinkle** [comment]
_Exported to <https://phabricator.wikimedia.org/T327038>._
